apiVersion: v1
kind: Pod
metadata:
  name: conversor
  labels:
    app: conversor
spec:
  containers:
    - name: site
      image: eduardopsy/conversao-temperatura:latest
      ports:
        - containerPort: 80
