apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
        - name: site
          image: eduardopsy/conversao-temperatura:latest
          ports:
              - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: deployment-service
spec:
  selector:
    app: conversor
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  type: NodePort