name: CI

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  CI:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2

      - name: Setup do Node.JS
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.16.0

      - name: Instalação do Mocha e dos pacotes para teste
        run: |
          cd src;
          npm install -g mocha;
          npm install
      
      - name: Execução dos testes do projeto
        run: mocha src/test/convert.js

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Construção da Imagem Docker
        uses: docker/build-push-action@v4.1.1
        with:
          context: src
          file: src/Dockerfile
          push: true
          tags:
            eduardopsy/conversao-temperatura
